export const GET_GAMES = 'GET_GAMES';
export const SET_LOADING = 'SET_LOADING';
export const LOGS_ERROR = 'LOGS_ERROR';
export const GET_GAME_EVENTS = 'GET_GAME_EVENTS';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_CURRENT_LEAGUE = 'SET_CURRENT_LEAGUE';
export const GET_LEAGUE_STANDINGS = 'GET_LEAGUE_STANDINGS';
export const GET_LEAGUE_TOP_SCORERS = 'GET_LEAGUE_TOP_SCORERS'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';